name: recipe_recommender_frontend
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=2.18.2 <3.0.0'

dependencies:
  path_provider: ^2.0.11
  flutter_pw_validator: ^1.4.2
  email_validator: '^2.1.16'
  http: ^0.13.5
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  persistent_bottom_nav_bar: ^5.0.2
  flutter_svg: ^1.1.6
  filter_list: ^1.0.2
  flutter_typeahead: ^4.1.1
  substring_highlight: ^1.0.33
  expansion_tile_card: ^2.0.0
  syncfusion_flutter_charts: ^20.3.61
  flutter_staggered_grid_view: ^0.6.2
  share_plus: ^6.3.0
  settings_ui: ^2.0.2
dev_dependencies:
  network_image_mock: ^2.0.1
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:

  uses-material-design: true

  assets:
    - assets/images/

  fonts:
    - family: Satoshi
      fonts:
        - asset: assets/fonts/Satoshi-Medium.ttf
    - family: Telma
      fonts:
        - asset: assets/fonts/Telma-Medium.ttf
    - family: Arslan
      fonts:
        - asset: assets/fonts/ArbFONTS-Arslan-Wessam-B.ttf
    - family: Roboto
      fonts:
        - asset: assets/fonts/Roboto-Bold.ttf
        - asset: assets/fonts/Roboto-BoldItalic.ttf
        - asset: assets/fonts/Roboto-Italic.ttf
        - asset: assets/fonts/Roboto-Medium.ttf
        - asset: assets/fonts/Roboto-MediumItalic.ttf
        - asset: assets/fonts/Roboto-Regular.ttf