# This workflow will build a Java project with Gradle and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-java-with-gradle

name: Java

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  BrainFoodEndPoint: jdbc:postgresql://db.ohqnkjfaffdkgvzybdwu.supabase.co:5432/postgres
  BrainFoodPassword: OQf40nKStUpXrDGQ
  BrainFoodUsername: postgres
  
permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./backend
        
    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
    - name: Make gradlew executable
      run: chmod +x ./gradlew
    - name: Build with Gradle
      uses: gradle/gradle-build-action@67421db6bd0bf253fb4bd25b31ebb98943c375e1
      with:
        arguments: build
        build-root-directory: ./backend
